name: Optimize and Deploy Resource Pack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip Resource Pack
        run: |
          zip -r pack.zip assets/ pack.mcmeta

      - name: Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "latest"
          name: "Latest Pack Build"
          draft: false
          prerelease: false
          files: |
            pack.zip
